spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/spring-training
    username: spring-training_user
    password: spring-training
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: kafka:9092
    properties:
      schema:
        registry:
          cache-capacity: 10000
          url: http://schema-registry:8085
  graylog:
    host: graylog
    port: 12201
    
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, refresh, env, configprops
  endpoint:
    health:
      show-details: always
  info:
    app:
      name: Spring Training Service
      version: 1.0.0
