spring:
  application:
    name: Spring Training Config Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/andreazemi94/SpringTraining
          clone-on-start: true
          default-label: main
          search-paths:
            - config/dev
            - config/prod
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, health, info