spring:
  application:
    name: Spring Training Config Server
  cloud:
    cloud:
      bus:
        enabled: true
    config:
      server:
        git:
          uri: https://github.com/andreazemi94/SpringTraining
          clone-on-start: true
          default-label: main
          search-paths:
            - config/dev
            - config/prod
    kafka:
      bootstrap-servers: "${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}"
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, health, info