spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/spring-training
    username: spring-training_user
    password: spring-training
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:29092
    properties:
      schema:
        registry:
          cache-capacity: 10000
          url: http://localhost:8085

  graylog:
    host: localhost
    port: 12201
    
  cloud:
    bus:
      enabled: true
    stream:
      bindings:
        springCloudBusInput:
          destination: springCloudBus
          consumer:
            content-type: application/json
      kafka:
        bindings:
          springCloudBusInput:
            consumer:
              # Forza l'uso dello String deserializer per il bus
              value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          springCloudBusOutput:
            producer:
              # Forza l'uso dello String serializer per il bus
              value-serializer: org.apache.kafka.common.serialization.StringSerializer
