spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-training
    username: spring-training_user
    password: spring-training
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:29092
    properties:
      schema:
        registry:
          cache-capacity: 10000
          url: http://localhost:8085
  graylog:
    host: localhost
    port: 12201
    
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, refresh, env, configprops, busrefresh
  endpoint:
    health:
      show-details: always
  info:
    app:
      name: Spring Training Service
      version: 1.0.0
      
resilience4j:
  retry:
    instances:
        externalService:
            maxAttempts: 3
            waitDuration: 10s
            enableExponentialBackoff: true
            exponentialBackoffMultiplier: 2
            retryExceptions:
                - java.lang.RuntimeException
            ignoreExceptions:
                - io.github.robwin.exception.BusinessException
  circuitbreaker:
    instances:
      externalService:
        slidingWindowSize: 10           # Analizza le ultime 10 richieste
        failureRateThreshold: 50        # Si apre se il 50% fallisce
        waitDurationInOpenState: 10s    # Resta aperto per 10 secondi
        permittedNumberOfCallsInHalfOpenState: 3  # In Half-Open permette 3 chiamate di test
        registerHealthIndicator: true   # Mostra lo stato in Actuator
