spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/spring-training
    username: spring-training_user
    password: spring-training
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:29092
    properties:
      schema:
        registry:
          cache-capacity: 10000
          url: http://localhost:8085

  graylog:
    host: localhost
    port: 12201

  security:
    jwt:
      secret-key: my-secret-key
      expiration-time: 86400000
    oauth2:
      client:
        registration:
          google:
            client-id: 889281652725-qto4qlcsgjah8qq04or1sc0o79dvlf1h.apps.googleusercontent.com
            client-secret: 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
            scope: 
              - openid
              - profile
              - email
