spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-training
    username: spring-training_user
    password: spring-training
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:29092
    properties:
      schema:
        registry:
          cache-capacity: 10000
          url: http://localhost:8085
  graylog:
    host: localhost
    port: 12201
    
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, refresh, env, configprops, resilience4j
  endpoint:
    health:
      show-details: always
  info:
    app:
      name: Spring Training Service
      version: 1.0.0
      
resilience4j:
  timelimiter:
    instances:
      externalService:
        timeoutDuration: 500ms
        cancelRunningFuture: true
  ratelimiter:
    instances:
      externalService:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 1s
  retry:
    instances:
        externalService:
            maxAttempts: 3  
            waitDuration: 10s 
            enableExponentialBackoff: true 
            exponentialBackoffMultiplier: 2  
            retryExceptions:
                - java.lang.RuntimeException 
            ignoreExceptions:  
                - java.lang.ArithmeticException 
  circuitbreaker:
    instances:
      externalService:
        slidingWindowSize: 10          
        failureRateThreshold: 50       
        waitDurationInOpenState: 10s    
        permittedNumberOfCallsInHalfOpenState: 3  
        registerHealthIndicator: true   
