spring:
  application:
    name: order-microservice
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: order-microservice
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://localhost:8095/realms/SpringTraining
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8095/realms/SpringTraining/protocol/openid-connect/certs
  kafka:
    topic:
      order: com.springtraining.order.messages
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
server:
  port: 8081
