keycloak:
	resource: order-microservice
		credentials:
		  secret: <client-secret>
spring:
  application:
    name: order-microservice
  kafka:
    topic:
      order: com.springtraining.order.messages
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
server:
  port: 8081
