spring:
  application:
    name: order-microservice
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8095/realms/Spring%20Training  # URI del realm di Keycloak
          jwk-set-uri: http://localhost:8095/realms/Spring%20Training/protocol/openid-connect/certs  # Endpoint per i certificati pubblici
  kafka:
    topic:
      order: com.springtraining.order.messages
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
server:
  port: 8081
